sudo: required
dist: trusty
language: python
python:
  - "3.6"
env:
  - CI_TEST=true
  - FLASK_APP=wsgi:app
before_install:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
  - sudo apt-get install nodejs
install:
  - pip install -r requirements.txt
  - cd web
  - npm install
  - npm run build
  - cd ..
before_script:
  - flask run &
  - sleep 3
script:
- pytest tests/